version: 2

project_name: asa-cli

builds:
  - main: .
    binary: asa-cli
    ldflags:
      - -s -w
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

brews:
  - repository:
      owner: TrebuhS
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    name: asa-cli
    homepage: "https://github.com/TrebuhS/Apple-Search-Ads-CLI"
    description: "CLI for the Apple Search Ads Campaign Management API v5"
    license: "MIT"
    test: |
      assert_match "Apple Search Ads", shell_output("#{bin}/asa-cli --help")
